#!name=Blurrr Premium Unlock
#!desc=Unlock Blurrr Video Editor Premium Features
#!author=explicit7x
#!homepage=https://github.com/explicit7x/shadowrocket-scripts
#!icon=https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/app-icon.png

[General]
bypass-system = true
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = system
ipv6 = false
prefer-ipv6 = false
update-url = https://raw.githubusercontent.com/explicit7x/shadowrocket-scripts/main/blurrr.conf

[Rule]
FINAL,DIRECT

[Host]
localhost = 127.0.0.1

[URL Rewrite]

[Script]
blurrr_premium = type=http-response,pattern=^https?:\/\/video-beats-api\.360in\.com\/v1\/multi-json-config-show,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/explicit7x/shadowrocket-scripts/main/blurrr.js,script-update-interval=86400,timeout=10,enable=true

[MITM]
hostname = video-beats-api.360in.com
enable = true
